remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: HD Radio
description: HD (High Definition) Streams of online radio stations - because DAB+ digital radio sounds crap
